exports.recipesConst = [
  {
    id: 716426,
    title: "Cauliflower, Brown Rice, and Vegetable Fried Rice",
    image: "https://spoonacular.com/recipeImages/716426-312x231.jpg",
    dishTypes: ["side dish"],
    summary:
      'Cauliflower, Brown Rice, and Vegetable Fried Rice might be a good recipe to expand your side dish recipe box. Watching your figure? This gluten free, dairy free, lacto ovo vegetarian, and vegan recipe has <b>192 calories</b>, <b>7g of protein</b>, and <b>6g of fat</b> per serving. For <b>$1.12 per serving</b>, this recipe <b>covers 19%</b> of your daily requirements of vitamins and minerals. This recipe serves 8. This recipe from fullbellysisters.blogspot.com has 3689 fans. This recipe is typical of Chinese cuisine. From preparation to the plate, this recipe takes about <b>30 minutes</b>. Head to the store and pick up peas, broccoli, salt, and a few other things to make it today. Overall, this recipe earns an <b>awesome spoonacular score of 100%</b>. Users who liked this recipe also liked <a href="https://spoonacular.com/recipes/vegetable-fried-brown-rice-36199">Vegetable Fried Brown Rice</a>, <a href="https://spoonacular.com/recipes/vegetable-fried-cauliflower-rice-933261">Vegetable Fried Cauliflower Rice</a>, and <a href="https://spoonacular.com/recipes/easy-vegetable-fried-brown-rice-with-egg-802042">Easy Vegetable Fried Brown Rice with Egg</a>.',
    healthScore: 76,
    instructions:
      "<ol><li><span></span>Remove the cauliflower's tough stem and reserve for another use. Using a food processor, pulse cauliflower florets until they resemble rice or couscous. You should end up with around four cups of \"cauliflower rice.\"</li><li>Heat 1T butter and 1T oil in a large skillet over medium heat. Add garlic and the white and light green pieces of scallion. Sauté about a minute.</li><li>Add the cauliflower to the pan. Stir to coat with oil, then spread out in pan and let sit; you want it cook a bit and to caramelize (get a bit brown), which will bring out the sweetness. After a couple of minutes, stir and spread out again.</li><li>Add cold rice (it separates easily, so it won't clump up during cooking), plus the additional grapeseed and coconut oil or butter. Raise heat to medium-high. Toss everything together and, again, spread the mixture out over the whole pan and press a bit into the bottom. Let it sit for about two minutes—so the rice can get toasted and a little crispy. Add the peas and broccoli and stir again. Drizzle soy sauce and toasted sesame oil over rice.</li><li>Cook for another minute or so and turn off heat. Add chopped scallion tops and toss.</li><li>I like to toast some sesame seeds in a dry pan; I sprinkle these and some more raw, chopped scallion over the top of the rice for added flavor and crunch.</li><li>Season to taste with salt and, if you'd like, more soy sauce. Keep in mind that if you're serving this with something salty and saucy (ie. teriyaki chicken) you may want to hold off on adding too much salt to the fried rice.</li></ol>",
    diets: ["gluten free", "dairy free", "lacto ovo vegetarian", "vegan"],
  },
  {
    id: 715594,
    title: "Homemade Garlic and Basil French Fries",
    image: "https://spoonacular.com/recipeImages/715594-312x231.jpg",
    dishTypes: ["lunch", "main course", "main dish", "dinner"],
    summary:
      'The recipe Homemade Garlic and Basil French Fries is ready <b>in roughly 45 minutes</b> and is definitely a super <b>vegan</b> option for lovers of American food. One serving contains <b>596 calories</b>, <b>18g of protein</b>, and <b>15g of fat</b>. For <b>83 cents per serving</b>, you get a side dish that serves 2. Several people made this recipe, and 1669 would say it hit the spot. If you have garlic salt, flour, garlic powder, and a few other ingredients on hand, you can make it. All things considered, we decided this recipe <b>deserves a spoonacular score of 100%</b>. This score is outstanding. Try <a href="https://spoonacular.com/recipes/homemade-french-fries-with-fresh-garlic-and-dill-494220">Homemade French Fries with Fresh Garlic and Dill</a>, <a href="https://spoonacular.com/recipes/roasted-garlic-french-fries-519898">Roasted Garlic French Fries</a>, and <a href="https://spoonacular.com/recipes/sweet-potato-fries-with-basil-salt-and-garlic-mayonnaise-120735">Sweet Potato Fries With Basil Salt and Garlic Mayonnaise</a> for similar recipes.',
    healthScore: 77,
    instructions:
      "<ol><li><span></span>Remove the cauliflower's tough stem and reserve for another use. Using a food processor, pulse cauliflower florets until they resemble rice or couscous. You should end up with around four cups of \"cauliflower rice.\"</li><li>Heat 1T butter and 1T oil in a large skillet over medium heat. Add garlic and the white and light green pieces of scallion. Sauté about a minute.</li><li>Add the cauliflower to the pan. Stir to coat with oil, then spread out in pan and let sit; you want it cook a bit and to caramelize (get a bit brown), which will bring out the sweetness. After a couple of minutes, stir and spread out again.</li><li>Add cold rice (it separates easily, so it won't clump up during cooking), plus the additional grapeseed and coconut oil or butter. Raise heat to medium-high. Toss everything together and, again, spread the mixture out over the whole pan and press a bit into the bottom. Let it sit for about two minutes—so the rice can get toasted and a little crispy. Add the peas and broccoli and stir again. Drizzle soy sauce and toasted sesame oil over rice.</li><li>Cook for another minute or so and turn off heat. Add chopped scallion tops and toss.</li><li>I like to toast some sesame seeds in a dry pan; I sprinkle these and some more raw, chopped scallion over the top of the rice for added flavor and crunch.</li><li>Season to taste with salt and, if you'd like, more soy sauce. Keep in mind that if you're serving this with something salty and saucy (ie. teriyaki chicken) you may want to hold off on adding too much salt to the fried rice.</li></ol>",
    diets: ["dairy free", "ovo vegetarian", "vegan"],
  },
  {
    id: 715497,
    title: "Berry Banana Breakfast Smoothie",
    image: "https://spoonacular.com/recipeImages/715497-312x231.jpg",
    dishTypes: ["morning meal", "brunch", "breakfast"],
    summary:
      'If you have around <b>5 minutes</b> to spend in the kitchen, Berry Banana Breakfast Smoothie might be a tremendous <b>lacto ovo vegetarian</b> recipe to try. This recipe makes 1 servings with <b>501 calories</b>, <b>21g of protein</b>, and <b>11g of fat</b> each. For <b>$2.19 per serving</b>, this recipe <b>covers 32%</b> of your daily requirements of vitamins and minerals. 688 people found this recipe to be tasty and satisfying. It is brought to you by Pink When. Head to the store and pick up graham crackers, soy milk, banana, and a few other things to make it today. It works well as a morn meal. Overall, this recipe earns a <b>super spoonacular score of 100%</b>. If you like this recipe, take a look at these similar recipes: <a href="https://spoonacular.com/recipes/berry-banana-breakfast-smoothie-249239">Berry Banana Breakfast Smoothie</a>, <a href="https://spoonacular.com/recipes/berry-and-banana-oat-breakfast-smoothie-626817">Berry and Bananan Oat Breakfast Smoothie</a>, and <a href="https://spoonacular.com/recipes/berry-breakfast-smoothie-774875">Berry Breakfast Smoothie</a>.',
    healthScore: 63,
    instructions:
      "<ol><li><span></span>Remove the cauliflower's tough stem and reserve for another use. Using a food processor, pulse cauliflower florets until they resemble rice or couscous. You should end up with around four cups of \"cauliflower rice.\"</li><li>Heat 1T butter and 1T oil in a large skillet over medium heat. Add garlic and the white and light green pieces of scallion. Sauté about a minute.</li><li>Add the cauliflower to the pan. Stir to coat with oil, then spread out in pan and let sit; you want it cook a bit and to caramelize (get a bit brown), which will bring out the sweetness. After a couple of minutes, stir and spread out again.</li><li>Add cold rice (it separates easily, so it won't clump up during cooking), plus the additional grapeseed and coconut oil or butter. Raise heat to medium-high. Toss everything together and, again, spread the mixture out over the whole pan and press a bit into the bottom. Let it sit for about two minutes—so the rice can get toasted and a little crispy. Add the peas and broccoli and stir again. Drizzle soy sauce and toasted sesame oil over rice.</li><li>Cook for another minute or so and turn off heat. Add chopped scallion tops and toss.</li><li>I like to toast some sesame seeds in a dry pan; I sprinkle these and some more raw, chopped scallion over the top of the rice for added flavor and crunch.</li><li>Season to taste with salt and, if you'd like, more soy sauce. Keep in mind that if you're serving this with something salty and saucy (ie. teriyaki chicken) you may want to hold off on adding too much salt to the fried rice.</li></ol>",
    diets: ["lacto ovo vegetarian"],
  },
  {
    id: 644387,
    title: "Garlicky Kale",
    image: "https://spoonacular.com/recipeImages/644387-312x231.jpg",
    dishTypes: ["side dish"],
    summary:
      'Garlicky Kale might be just the side dish you are searching for. This caveman, gluten free, primal, and whole 30 recipe serves 2 and costs <b>69 cents per serving</b>. One serving contains <b>179 calories</b>, <b>3g of protein</b>, and <b>15g of fat</b>. A few people made this recipe, and 17 would say it hit the spot. If you have olive oil, garlic, curly kale, and a few other ingredients on hand, you can make it. From preparation to the plate, this recipe takes around <b>45 minutes</b>. All things considered, we decided this recipe <b>deserves a spoonacular score of 99%</b>. This score is awesome. Try <a href="https://spoonacular.com/recipes/garlicky-kale-248759">Garlicky Kale</a>, <a href="https://spoonacular.com/recipes/garlicky-kale-14910">Garlicky Kale</a>, and <a href="https://spoonacular.com/recipes/garlicky-kale-crostini-15010">Garlicky Kale Crostini</a> for similar recipes.',
    healthScore: 92,
    instructions:
      "<ol><li><span></span>Remove the cauliflower's tough stem and reserve for another use. Using a food processor, pulse cauliflower florets until they resemble rice or couscous. You should end up with around four cups of \"cauliflower rice.\"</li><li>Heat 1T butter and 1T oil in a large skillet over medium heat. Add garlic and the white and light green pieces of scallion. Sauté about a minute.</li><li>Add the cauliflower to the pan. Stir to coat with oil, then spread out in pan and let sit; you want it cook a bit and to caramelize (get a bit brown), which will bring out the sweetness. After a couple of minutes, stir and spread out again.</li><li>Add cold rice (it separates easily, so it won't clump up during cooking), plus the additional grapeseed and coconut oil or butter. Raise heat to medium-high. Toss everything together and, again, spread the mixture out over the whole pan and press a bit into the bottom. Let it sit for about two minutes—so the rice can get toasted and a little crispy. Add the peas and broccoli and stir again. Drizzle soy sauce and toasted sesame oil over rice.</li><li>Cook for another minute or so and turn off heat. Add chopped scallion tops and toss.</li><li>I like to toast some sesame seeds in a dry pan; I sprinkle these and some more raw, chopped scallion over the top of the rice for added flavor and crunch.</li><li>Season to taste with salt and, if you'd like, more soy sauce. Keep in mind that if you're serving this with something salty and saucy (ie. teriyaki chicken) you may want to hold off on adding too much salt to the fried rice.</li></ol>",
    diets: [
      "gluten free",
      "dairy free",
      "paleolithic",
      "lacto ovo vegetarian",
      "primal",
      "whole 30",
      "vegan",
    ],
  },
  {
    id: 716268,
    title: "African Chicken Peanut Stew",
    image: "https://spoonacular.com/recipeImages/716268-312x231.jpg",
    dishTypes: ["lunch", "main course", "main dish", "dinner"],
    summary:
      'Need a <b>gluten free and dairy free main course</b>? African Chicken Peanut Stew could be a tremendous recipe to try. This recipe makes 1 servings with <b>1377 calories</b>, <b>75g of protein</b>, and <b>102g of fat</b> each. For <b>$3.87 per serving</b>, this recipe <b>covers 62%</b> of your daily requirements of vitamins and minerals. It can be enjoyed any time, but it is especially good for <b>Autumn</b>. From preparation to the plate, this recipe takes approximately <b>45 minutes</b>. 124 people have tried and liked this recipe. Head to the store and pick up bell peppers, tomato, pepper, and a few other things to make it today. To use up the tomato you could follow this main course with the <a href="https://spoonacular.com/recipes/pink-peony-popcorn-balls-129348">Pink Peony Popcorn Balls</a> as a dessert. All things considered, we decided this recipe <b>deserves a spoonacular score of 99%</b>. This score is super. Try <a href="https://spoonacular.com/recipes/african-chicken-peanut-stew-245461">African Chicken Peanut Stew</a>, <a href="https://spoonacular.com/recipes/west-african-peanut-chicken-stew-163315">West African Peanut-Chicken Stew</a>, and <a href="https://spoonacular.com/recipes/one-pot-african-peanut-stew-854978">One-Pot African Peanut Stew</a> for similar recipes.',
    healthScore: 100,
    instructions:
      "<ol><li><span></span>Remove the cauliflower's tough stem and reserve for another use. Using a food processor, pulse cauliflower florets until they resemble rice or couscous. You should end up with around four cups of \"cauliflower rice.\"</li><li>Heat 1T butter and 1T oil in a large skillet over medium heat. Add garlic and the white and light green pieces of scallion. Sauté about a minute.</li><li>Add the cauliflower to the pan. Stir to coat with oil, then spread out in pan and let sit; you want it cook a bit and to caramelize (get a bit brown), which will bring out the sweetness. After a couple of minutes, stir and spread out again.</li><li>Add cold rice (it separates easily, so it won't clump up during cooking), plus the additional grapeseed and coconut oil or butter. Raise heat to medium-high. Toss everything together and, again, spread the mixture out over the whole pan and press a bit into the bottom. Let it sit for about two minutes—so the rice can get toasted and a little crispy. Add the peas and broccoli and stir again. Drizzle soy sauce and toasted sesame oil over rice.</li><li>Cook for another minute or so and turn off heat. Add chopped scallion tops and toss.</li><li>I like to toast some sesame seeds in a dry pan; I sprinkle these and some more raw, chopped scallion over the top of the rice for added flavor and crunch.</li><li>Season to taste with salt and, if you'd like, more soy sauce. Keep in mind that if you're serving this with something salty and saucy (ie. teriyaki chicken) you may want to hold off on adding too much salt to the fried rice.</li></ol>",
    diets: ["gluten free", "dairy free"],
  },
  {
    id: 716381,
    title: "Nigerian Snail Stew",
    image: "https://spoonacular.com/recipeImages/716381-312x231.jpg",
    dishTypes: ["lunch", "main course", "main dish", "dinner"],
    summary:
      'Nigerian Snail Stew might be just the main course you are searching for. For <b>$9.08 per serving</b>, this recipe <b>covers 45%</b> of your daily requirements of vitamins and minerals. This recipe makes 1 servings with <b>363 calories</b>, <b>23g of protein</b>, and <b>5g of fat</b> each. Plenty of people made this recipe, and 361 would say it hit the spot. If you have chili powder, snails, limes, and a few other ingredients on hand, you can make it. To use up the ice cubes you could follow this main course with the <a href="https://spoonacular.com/recipes/nectarine-blackberry-and-pecan-sundaes-50465">Nectarine, Blackberry, and Pecan Sundaes</a> as a dessert. It can be enjoyed any time, but it is especially good for <b>Autumn</b>. It is a good option if you re following a <b>gluten free, dairy free, and whole 30</b> diet. All things considered, we decided this recipe <b>deserves a spoonacular score of 99%</b>. This score is spectacular. Try <a href="https://spoonacular.com/recipes/nigerian-kidney-bean-stew-with-a-peanut-sauce-112643">Nigerian Kidney Bean Stew With a Peanut Sauce</a>, <a href="https://spoonacular.com/recipes/little-snail-rolls-369096">Little Snail Rolls</a>, and <a href="https://spoonacular.com/recipes/maple-snail-cookies-76877">Maple Snail Cookies</a> for similar recipes.',
    healthScore: 89,
    instructions:
      "<ol><li><span></span>Remove the cauliflower's tough stem and reserve for another use. Using a food processor, pulse cauliflower florets until they resemble rice or couscous. You should end up with around four cups of \"cauliflower rice.\"</li><li>Heat 1T butter and 1T oil in a large skillet over medium heat. Add garlic and the white and light green pieces of scallion. Sauté about a minute.</li><li>Add the cauliflower to the pan. Stir to coat with oil, then spread out in pan and let sit; you want it cook a bit and to caramelize (get a bit brown), which will bring out the sweetness. After a couple of minutes, stir and spread out again.</li><li>Add cold rice (it separates easily, so it won't clump up during cooking), plus the additional grapeseed and coconut oil or butter. Raise heat to medium-high. Toss everything together and, again, spread the mixture out over the whole pan and press a bit into the bottom. Let it sit for about two minutes—so the rice can get toasted and a little crispy. Add the peas and broccoli and stir again. Drizzle soy sauce and toasted sesame oil over rice.</li><li>Cook for another minute or so and turn off heat. Add chopped scallion tops and toss.</li><li>I like to toast some sesame seeds in a dry pan; I sprinkle these and some more raw, chopped scallion over the top of the rice for added flavor and crunch.</li><li>Season to taste with salt and, if you'd like, more soy sauce. Keep in mind that if you're serving this with something salty and saucy (ie. teriyaki chicken) you may want to hold off on adding too much salt to the fried rice.</li></ol>",
    diets: ["gluten free", "dairy free", "paleolithic", "primal", "whole 30"],
  },
  {
    id: 782601,
    title: "Red Kidney Bean Jambalaya",
    image: "https://spoonacular.com/recipeImages/782601-312x231.jpg",
    dishTypes: ["lunch", "main course", "main dish", "dinner"],
    summary:
      'Red Kidney Bean Jambalaya might be just the <b>Creole</b> recipe you are searching for. One serving contains <b>538 calories</b>, <b>21g of protein</b>, and <b>8g of fat</b>. For <b>$1.69 per serving</b>, this recipe <b>covers 34%</b> of your daily requirements of vitamins and minerals. This recipe from foodandspice.blogspot.com has 52 fans. A few people really liked this main course. Head to the store and pick up brown rice, vegetable stock, liquid smoke, and a few other things to make it today. To use up the sea salt you could follow this main course with the <a href="https://spoonacular.com/recipes/raspberry-sea-salt-brownies-494161">Raspberry Sea Salt Brownies</a> as a dessert. From preparation to the plate, this recipe takes about <b>45 minutes</b>. All things considered, we decided this recipe <b>deserves a spoonacular score of 99%</b>. This score is spectacular. Try <a href="https://spoonacular.com/recipes/red-kidney-bean-dip-148569">Red Kidney Bean Dip</a>, <a href="https://spoonacular.com/recipes/kidney-bean-dip-119992">Kidney Bean Dip</a>, and <a href="https://spoonacular.com/recipes/red-kidney-bean-curry-80686">Red Kidney Bean Curry</a> for similar recipes.',
    healthScore: 100,
    instructions:
      "<ol><li><span></span>Remove the cauliflower's tough stem and reserve for another use. Using a food processor, pulse cauliflower florets until they resemble rice or couscous. You should end up with around four cups of \"cauliflower rice.\"</li><li>Heat 1T butter and 1T oil in a large skillet over medium heat. Add garlic and the white and light green pieces of scallion. Sauté about a minute.</li><li>Add the cauliflower to the pan. Stir to coat with oil, then spread out in pan and let sit; you want it cook a bit and to caramelize (get a bit brown), which will bring out the sweetness. After a couple of minutes, stir and spread out again.</li><li>Add cold rice (it separates easily, so it won't clump up during cooking), plus the additional grapeseed and coconut oil or butter. Raise heat to medium-high. Toss everything together and, again, spread the mixture out over the whole pan and press a bit into the bottom. Let it sit for about two minutes—so the rice can get toasted and a little crispy. Add the peas and broccoli and stir again. Drizzle soy sauce and toasted sesame oil over rice.</li><li>Cook for another minute or so and turn off heat. Add chopped scallion tops and toss.</li><li>I like to toast some sesame seeds in a dry pan; I sprinkle these and some more raw, chopped scallion over the top of the rice for added flavor and crunch.</li><li>Season to taste with salt and, if you'd like, more soy sauce. Keep in mind that if you're serving this with something salty and saucy (ie. teriyaki chicken) you may want to hold off on adding too much salt to the fried rice.</li></ol>",
    diets: ["gluten free", "dairy free", "lacto ovo vegetarian", "vegan"],
  },
  {
    id: 794349,
    title: "Broccoli and Chickpea Rice Salad",
    image: "https://spoonacular.com/recipeImages/794349-312x231.jpg",
    dishTypes: ["lunch", "main course", "main dish", "dinner"],
    summary:
      'Need a <b>gluten free and vegan main course</b>? Broccoli and Chickpea Rice Salad could be a spectacular recipe to try. One serving contains <b>524 calories</b>, <b>19g of protein</b>, and <b>12g of fat</b>. For <b>$1.38 per serving</b>, this recipe <b>covers 36%</b> of your daily requirements of vitamins and minerals. Head to the store and pick up almonds, olive oil, 2 tablespoons pineapple juice (juice from canned pineapple), and a few other things to make it today. 42 people have made this recipe and would make it again. From preparation to the plate, this recipe takes approximately <b>45 minutes</b>. All things considered, we decided this recipe <b>deserves a spoonacular score of 99%</b>. This score is spectacular. Similar recipes include <a href="https://spoonacular.com/recipes/easy-balsamic-chickpea-brown-rice-broccoli-salad-101160">Easy Balsamic Chickpea, Brown Rice & Broccoli Salad</a>, <a href="https://spoonacular.com/recipes/super-easy-chickpea-brown-rice-broccoli-crockpot-casserole-584241">Super Easy Chickpea, Brown Rice & Broccoli Crockpot Casserole</a>, and <a href="https://spoonacular.com/recipes/chickpea-and-broccoli-salad-29686">Chickpean And Broccoli Salad</a>.',
    healthScore: 100,
    instructions:
      "<ol><li><span></span>Remove the cauliflower's tough stem and reserve for another use. Using a food processor, pulse cauliflower florets until they resemble rice or couscous. You should end up with around four cups of \"cauliflower rice.\"</li><li>Heat 1T butter and 1T oil in a large skillet over medium heat. Add garlic and the white and light green pieces of scallion. Sauté about a minute.</li><li>Add the cauliflower to the pan. Stir to coat with oil, then spread out in pan and let sit; you want it cook a bit and to caramelize (get a bit brown), which will bring out the sweetness. After a couple of minutes, stir and spread out again.</li><li>Add cold rice (it separates easily, so it won't clump up during cooking), plus the additional grapeseed and coconut oil or butter. Raise heat to medium-high. Toss everything together and, again, spread the mixture out over the whole pan and press a bit into the bottom. Let it sit for about two minutes—so the rice can get toasted and a little crispy. Add the peas and broccoli and stir again. Drizzle soy sauce and toasted sesame oil over rice.</li><li>Cook for another minute or so and turn off heat. Add chopped scallion tops and toss.</li><li>I like to toast some sesame seeds in a dry pan; I sprinkle these and some more raw, chopped scallion over the top of the rice for added flavor and crunch.</li><li>Season to taste with salt and, if you'd like, more soy sauce. Keep in mind that if you're serving this with something salty and saucy (ie. teriyaki chicken) you may want to hold off on adding too much salt to the fried rice.</li></ol>",
    diets: ["gluten free", "dairy free", "lacto ovo vegetarian", "vegan"],
  },
  {
    id: 715446,
    title: "Slow Cooker Beef Stew",
    image: "https://spoonacular.com/recipeImages/715446-312x231.jpg",
    dishTypes: ["lunch", "main course", "main dish", "dinner"],
    summary:
      'If you want to add more <b>gluten free and dairy free</b> recipes to your recipe box, Slow Cooker Beef Stew might be a recipe you should try. One portion of this dish contains approximately <b>52g of protein</b>, <b>16g of fat</b>, and a total of <b>528 calories</b>. This recipe serves 6. For <b>$2.94 per serving</b>, this recipe <b>covers 45%</b> of your daily requirements of vitamins and minerals. 58 people found this recipe to be scrumptious and satisfying. It works well as a reasonably priced main course for <b>Winter</b>. A mixture of canned beef broth, carrots, green onions, and a handful of other ingredients are all it takes to make this recipe so yummy. From preparation to the plate, this recipe takes around <b>8 hours and 10 minutes</b>. It is brought to you by Pink When. All things considered, we decided this recipe <b>deserves a spoonacular score of 99%</b>. This score is super. If you like this recipe, take a look at these similar recipes: <a href="https://spoonacular.com/recipes/butternut-squash-beef-stew-instant-pot-pressure-cooker-or-slow-cooker-840470">Butternut Squash Beef Stew (Instant Pot, Pressure Cooker or Slow Cooker)</a>, <a href="https://spoonacular.com/recipes/slow-cooker-beef-stew-990111">Slow Cooker Beef Stew</a>, and <a href="https://spoonacular.com/recipes/slow-cooker-beef-stew-770894">Slow-Cooker Beef Stew</a>.',
    healthScore: 100,
    instructions:
      "<ol><li><span></span>Remove the cauliflower's tough stem and reserve for another use. Using a food processor, pulse cauliflower florets until they resemble rice or couscous. You should end up with around four cups of \"cauliflower rice.\"</li><li>Heat 1T butter and 1T oil in a large skillet over medium heat. Add garlic and the white and light green pieces of scallion. Sauté about a minute.</li><li>Add the cauliflower to the pan. Stir to coat with oil, then spread out in pan and let sit; you want it cook a bit and to caramelize (get a bit brown), which will bring out the sweetness. After a couple of minutes, stir and spread out again.</li><li>Add cold rice (it separates easily, so it won't clump up during cooking), plus the additional grapeseed and coconut oil or butter. Raise heat to medium-high. Toss everything together and, again, spread the mixture out over the whole pan and press a bit into the bottom. Let it sit for about two minutes—so the rice can get toasted and a little crispy. Add the peas and broccoli and stir again. Drizzle soy sauce and toasted sesame oil over rice.</li><li>Cook for another minute or so and turn off heat. Add chopped scallion tops and toss.</li><li>I like to toast some sesame seeds in a dry pan; I sprinkle these and some more raw, chopped scallion over the top of the rice for added flavor and crunch.</li><li>Season to taste with salt and, if you'd like, more soy sauce. Keep in mind that if you're serving this with something salty and saucy (ie. teriyaki chicken) you may want to hold off on adding too much salt to the fried rice.</li></ol>",
    diets: ["gluten free", "dairy free"],
  },
  {
    id: 715415,
    title: "Red Lentil Soup with Chicken and Turnips",
    image: "https://spoonacular.com/recipeImages/715415-312x231.jpg",
    dishTypes: ["soup"],
    summary:
      'Need a <b>gluten free and dairy free main course</b>? Red Lentil Soup with Chicken and Turnips could be an outstanding recipe to try. For <b>$2.8 per serving</b>, this recipe <b>covers 37%</b> of your daily requirements of vitamins and minerals. One serving contains <b>448 calories</b>, <b>23g of protein</b>, and <b>20g of fat</b>. Head to the store and pick up garlic, olive oil, celery stalks, and a few other things to make it today. It is perfect for <b>Autumn</b>. From preparation to the plate, this recipe takes about <b>55 minutes</b>. Plenty of people made this recipe, and 1866 would say it hit the spot. All things considered, we decided this recipe <b>deserves a spoonacular score of 99%</b>. This score is super. Try <a href="https://spoonacular.com/recipes/clean-eating-carrot-ginger-red-lentil-soup-921419">Clean Eating Carrot & Ginger Red Lentil Soup</a>, <a href="https://spoonacular.com/recipes/one-pot-red-lentil-sweet-potato-stew-928497">One-Pot Red Lentil Sweet Potato Stew</a>, and <a href="https://spoonacular.com/recipes/red-lentil-and-chicken-soup-682185">Red Lentil and Chicken Soup</a> for similar recipes.',
    healthScore: 73,
    instructions:
      "<ol><li><span></span>Remove the cauliflower's tough stem and reserve for another use. Using a food processor, pulse cauliflower florets until they resemble rice or couscous. You should end up with around four cups of \"cauliflower rice.\"</li><li>Heat 1T butter and 1T oil in a large skillet over medium heat. Add garlic and the white and light green pieces of scallion. Sauté about a minute.</li><li>Add the cauliflower to the pan. Stir to coat with oil, then spread out in pan and let sit; you want it cook a bit and to caramelize (get a bit brown), which will bring out the sweetness. After a couple of minutes, stir and spread out again.</li><li>Add cold rice (it separates easily, so it won't clump up during cooking), plus the additional grapeseed and coconut oil or butter. Raise heat to medium-high. Toss everything together and, again, spread the mixture out over the whole pan and press a bit into the bottom. Let it sit for about two minutes—so the rice can get toasted and a little crispy. Add the peas and broccoli and stir again. Drizzle soy sauce and toasted sesame oil over rice.</li><li>Cook for another minute or so and turn off heat. Add chopped scallion tops and toss.</li><li>I like to toast some sesame seeds in a dry pan; I sprinkle these and some more raw, chopped scallion over the top of the rice for added flavor and crunch.</li><li>Season to taste with salt and, if you'd like, more soy sauce. Keep in mind that if you're serving this with something salty and saucy (ie. teriyaki chicken) you may want to hold off on adding too much salt to the fried rice.</li></ol>",
    diets: ["gluten free", "dairy free"],
  },
  {
    id: 766453,
    title: "Hummus and Za'atar",
    image:
      "https://www.clara.es/medio/2021/12/16/que-comer-hoy_1962056a_1280x1167.jpg",
    dishTypes: ["lunch", "main course", "main dish", "dinner"],
    summary:
      'The recipe Hummus and Zaatar is ready <b>in around 45 minutes</b> and is definitely an outstanding <b>gluten free and vegan</b> option for lovers of middl eastern food. For <b>$1.61 per serving</b>, you get a marinade that serves 4. One serving contains <b>778 calories</b>, <b>34g of protein</b>, and <b>31g of fat</b>. This recipe from foodandspice.blogspot.com has 35 fans. If you have sea salt, garlic, juice of lemon, and a few other ingredients on hand, you can make it. All things considered, we decided this recipe <b>deserves a spoonacular score of 99%</b>. This score is excellent. Similar recipes include <a href="https://spoonacular.com/recipes/chopped-hummus-dip-with-zaatar-180958">Chopped Hummus Dip with Za’atar</a>, <a href="https://spoonacular.com/recipes/hummus-deviled-eggs-with-zaatar-exercise-challenge-626237">Hummus Deviled Eggs with Za’atar {Exercise Challenge}</a>, and <a href="https://spoonacular.com/recipes/zaatar-bread-rolls-manaiesh-bi-zaatar-132855">Za’atar Bread Rolls (Manaiesh Bi Za’atar)</a>.',
    healthScore: 100,
    instructions:
      "<ol><li><span></span>Remove the cauliflower's tough stem and reserve for another use. Using a food processor, pulse cauliflower florets until they resemble rice or couscous. You should end up with around four cups of \"cauliflower rice.\"</li><li>Heat 1T butter and 1T oil in a large skillet over medium heat. Add garlic and the white and light green pieces of scallion. Sauté about a minute.</li><li>Add the cauliflower to the pan. Stir to coat with oil, then spread out in pan and let sit; you want it cook a bit and to caramelize (get a bit brown), which will bring out the sweetness. After a couple of minutes, stir and spread out again.</li><li>Add cold rice (it separates easily, so it won't clump up during cooking), plus the additional grapeseed and coconut oil or butter. Raise heat to medium-high. Toss everything together and, again, spread the mixture out over the whole pan and press a bit into the bottom. Let it sit for about two minutes—so the rice can get toasted and a little crispy. Add the peas and broccoli and stir again. Drizzle soy sauce and toasted sesame oil over rice.</li><li>Cook for another minute or so and turn off heat. Add chopped scallion tops and toss.</li><li>I like to toast some sesame seeds in a dry pan; I sprinkle these and some more raw, chopped scallion over the top of the rice for added flavor and crunch.</li><li>Season to taste with salt and, if you'd like, more soy sauce. Keep in mind that if you're serving this with something salty and saucy (ie. teriyaki chicken) you may want to hold off on adding too much salt to the fried rice.</li></ol>",
    diets: ["gluten free", "dairy free", "lacto ovo vegetarian", "vegan"],
  },
  {
    id: 716627,
    title: "Easy Homemade Rice and Beans",
    image: "https://spoonacular.com/recipeImages/716627-312x231.jpg",
    dishTypes: ["lunch", "main course", "main dish", "dinner"],
    summary:
      'Need a <b>gluten free and vegan main course</b>? Easy Homemade Rice and Beans could be a great recipe to try. One serving contains <b>446 calories</b>, <b>19g of protein</b>, and <b>4g of fat</b>. For <b>$1.06 per serving</b>, this recipe <b>covers 26%</b> of your daily requirements of vitamins and minerals. 471 person have made this recipe and would make it again. A mixture of olive oil, ground pepper, onion, and a handful of other ingredients are all it takes to make this recipe so yummy. To use up the olive oil you could follow this main course with the <a href="https://spoonacular.com/recipes/sauteed-banana-granola-and-yogurt-parfait-624619">Sauteed Banana, Granolan and Yogurt Parfait</a> as a dessert. From preparation to the plate, this recipe takes approximately <b>35 minutes</b>. All things considered, we decided this recipe <b>deserves a spoonacular score of 99%</b>. This score is awesome. Try <a href="https://spoonacular.com/recipes/easy-homemade-refried-beans-619117">Easy homemade refried beans</a>, <a href="https://spoonacular.com/recipes/homemade-southern-red-beans-and-rice-243655">Homemade Southern Red Beans and Rice</a>, and <a href="https://spoonacular.com/recipes/skillet-chicken-with-homemade-rice-a-roni-and-green-beans-201454">Skillet Chicken with Homemade Rice-A-Roni and Green Beans</a> for similar recipes.',
    healthScore: 60,
    instructions:
      "<ol><li><span></span>Remove the cauliflower's tough stem and reserve for another use. Using a food processor, pulse cauliflower florets until they resemble rice or couscous. You should end up with around four cups of \"cauliflower rice.\"</li><li>Heat 1T butter and 1T oil in a large skillet over medium heat. Add garlic and the white and light green pieces of scallion. Sauté about a minute.</li><li>Add the cauliflower to the pan. Stir to coat with oil, then spread out in pan and let sit; you want it cook a bit and to caramelize (get a bit brown), which will bring out the sweetness. After a couple of minutes, stir and spread out again.</li><li>Add cold rice (it separates easily, so it won't clump up during cooking), plus the additional grapeseed and coconut oil or butter. Raise heat to medium-high. Toss everything together and, again, spread the mixture out over the whole pan and press a bit into the bottom. Let it sit for about two minutes—so the rice can get toasted and a little crispy. Add the peas and broccoli and stir again. Drizzle soy sauce and toasted sesame oil over rice.</li><li>Cook for another minute or so and turn off heat. Add chopped scallion tops and toss.</li><li>I like to toast some sesame seeds in a dry pan; I sprinkle these and some more raw, chopped scallion over the top of the rice for added flavor and crunch.</li><li>Season to taste with salt and, if you'd like, more soy sauce. Keep in mind that if you're serving this with something salty and saucy (ie. teriyaki chicken) you may want to hold off on adding too much salt to the fried rice.</li></ol>",
    diets: ["gluten free", "dairy free", "lacto ovo vegetarian", "vegan"],
  },
  {
    id: 716408,
    title: "Greek-Style Baked Fish: Fresh, Simple, and Delicious",
    image: "https://spoonacular.com/recipeImages/716408-312x231.jpg",
    dishTypes: ["lunch", "main course", "main dish", "dinner"],
    summary:
      'You can never have too many main course recipes, so give Greek-Style Baked Fish: Fresh, Simple, and Delicious a try. For <b>$3.04 per serving</b>, this recipe <b>covers 21%</b> of your daily requirements of vitamins and minerals. This recipe makes 4 servings with <b>345 calories</b>, <b>28g of protein</b>, and <b>12g of fat</b> each. This recipe is liked by 396 foodies and cooks. Head to the store and pick up salt & pepper, pepper, wine, and a few other things to make it today. To use up the cooked rice you could follow this main course with the <a href="https://spoonacular.com/recipes/breakfast-rice-pudding-547155">Breakfast Rice Pudding</a> as a dessert. From preparation to the plate, this recipe takes about <b>30 minutes</b>. It is a good option if you´re following a <b>gluten free and pescatarian</b> diet. All things considered, we decided this recipe <b>deserves a spoonacular score of 96%</b>. This score is awesome. Similar recipes include <a href="https://spoonacular.com/recipes/simple-greek-style-baked-fish-557560">Simple Greek Style Baked Fish</a>, <a href="https://spoonacular.com/recipes/greek-style-baked-fish-526858">Greek Style Baked Fish</a>, and <a href="https://spoonacular.com/recipes/delicious-greek-pastitsio-casserole-style-569500">Delicious Greek Pastitsio {Casserole-Style}</a>.',
    healthScore: 65,
    instructions:
      "<ol><li><span></span>Remove the cauliflower's tough stem and reserve for another use. Using a food processor, pulse cauliflower florets until they resemble rice or couscous. You should end up with around four cups of \"cauliflower rice.\"</li><li>Heat 1T butter and 1T oil in a large skillet over medium heat. Add garlic and the white and light green pieces of scallion. Sauté about a minute.</li><li>Add the cauliflower to the pan. Stir to coat with oil, then spread out in pan and let sit; you want it cook a bit and to caramelize (get a bit brown), which will bring out the sweetness. After a couple of minutes, stir and spread out again.</li><li>Add cold rice (it separates easily, so it won't clump up during cooking), plus the additional grapeseed and coconut oil or butter. Raise heat to medium-high. Toss everything together and, again, spread the mixture out over the whole pan and press a bit into the bottom. Let it sit for about two minutes—so the rice can get toasted and a little crispy. Add the peas and broccoli and stir again. Drizzle soy sauce and toasted sesame oil over rice.</li><li>Cook for another minute or so and turn off heat. Add chopped scallion tops and toss.</li><li>I like to toast some sesame seeds in a dry pan; I sprinkle these and some more raw, chopped scallion over the top of the rice for added flavor and crunch.</li><li>Season to taste with salt and, if you'd like, more soy sauce. Keep in mind that if you're serving this with something salty and saucy (ie. teriyaki chicken) you may want to hold off on adding too much salt to the fried rice.</li></ol>",
    diets: ["gluten free", "pescatarian"],
  },
  {
    id: 795751,
    title: "Chicken Fajita Stuffed Bell Pepper",
    image: "https://spoonacular.com/recipeImages/795751-312x231.jpg",
    dishTypes: ["lunch", "main course", "main dish", "dinner"],
    summary:
      'Chicken Fajita Stuffed Bell Pepper might be just the <b>Mexican</b> recipe you are searching for. One serving contains <b>561 calories</b>, <b>36g of protein</b>, and <b>24g of fat</b>. For <b>$2.96 per serving</b>, this recipe <b>covers 41%</b> of your daily requirements of vitamins and minerals. 159 people have tried and liked this recipe. It works best as a main course, and is done in approximately <b>45 minutes</b>. Head to the store and pick up medium/large avocado, cheese, chili powder, and a few other things to make it today. To use up the quinoa you could follow this main course with the <a href="https://spoonacular.com/recipes/quinoa-pudding-129583">Quinoa Pudding</a> as a dessert. It is a good option if you´re following a <b>gluten free</b> diet. All things considered, we decided this recipe <b>deserves a spoonacular score of 98%</b>. This score is tremendous. Try <a href="https://spoonacular.com/recipes/stuffed-bell-peppers-or-meatloaf-in-a-bell-pepper-551310">Stuffed Bell Peppers [or meatloaf in a bell pepper]</a>, <a href="https://spoonacular.com/recipes/stuffed-bell-pepper-526845">Stuffed Bell Pepper</a>, and <a href="https://spoonacular.com/recipes/stuffed-red-bell-pepper-rellenos-772739">Stuffed Red Bell Pepper Rellenos</a> for similar recipes.',
    healthScore: 75,
    instructions:
      "<ol><li><span></span>Remove the cauliflower's tough stem and reserve for another use. Using a food processor, pulse cauliflower florets until they resemble rice or couscous. You should end up with around four cups of \"cauliflower rice.\"</li><li>Heat 1T butter and 1T oil in a large skillet over medium heat. Add garlic and the white and light green pieces of scallion. Sauté about a minute.</li><li>Add the cauliflower to the pan. Stir to coat with oil, then spread out in pan and let sit; you want it cook a bit and to caramelize (get a bit brown), which will bring out the sweetness. After a couple of minutes, stir and spread out again.</li><li>Add cold rice (it separates easily, so it won't clump up during cooking), plus the additional grapeseed and coconut oil or butter. Raise heat to medium-high. Toss everything together and, again, spread the mixture out over the whole pan and press a bit into the bottom. Let it sit for about two minutes—so the rice can get toasted and a little crispy. Add the peas and broccoli and stir again. Drizzle soy sauce and toasted sesame oil over rice.</li><li>Cook for another minute or so and turn off heat. Add chopped scallion tops and toss.</li><li>I like to toast some sesame seeds in a dry pan; I sprinkle these and some more raw, chopped scallion over the top of the rice for added flavor and crunch.</li><li>Season to taste with salt and, if you'd like, more soy sauce. Keep in mind that if you're serving this with something salty and saucy (ie. teriyaki chicken) you may want to hold off on adding too much salt to the fried rice.</li></ol>",
    diets: ["gluten free"],
  },
  {
    id: 640941,
    title: "Crunchy Brussels Sprouts Side Dish",
    image: "https://spoonacular.com/recipeImages/640941-312x231.jpg",
    dishTypes: ["side dish"],
    summary:
      'Crunchy Brussels Sprouts Side Dish might be just the side dish you are searching for. This recipe makes 4 servings with <b>232 calories</b>, <b>8g of protein</b>, and <b>16g of fat</b> each. For <b>$1.69 per serving</b>, this recipe <b>covers 22%</b> of your daily requirements of vitamins and minerals. 26 people have tried and liked this recipe. If you have pepper, wine vinegar, dijon mustard, and a few other ingredients on hand, you can make it. From preparation to the plate, this recipe takes around <b>30 minutes</b>. It is a good option if you\'re following a <b>caveman, gluten free, dairy free, and primal</b> diet. All things considered, we decided this recipe <b>deserves a spoonacular score of 99%</b>. This score is spectacular. Try <a href="https://spoonacular.com/recipes/easy-side-dish-roasted-brussels-sprouts-and-grapes-474168">Easy Side Dish – Roasted Brussels Sprouts and Grapes</a>, <a href="https://spoonacular.com/recipes/csa-day-with-a-side-of-sauteed-brussels-sprouts-with-lemon-vinaigrette-534559">CSA Day with a Side of Sauteed Brussels Sprouts with Lemon Vinaigrette</a>, and <a href="https://spoonacular.com/recipes/thanksgiving-side-shredded-brussels-sprouts-with-persimmons-apricots-and-walnuts-574577">Thanksgiving Side : Shredded Brussels Sprouts with Persimmons, Apricots, and Walnuts</a> for similar recipes.',
    healthScore: 100,
    instructions:
      "<ol><li><span></span>Remove the cauliflower's tough stem and reserve for another use. Using a food processor, pulse cauliflower florets until they resemble rice or couscous. You should end up with around four cups of \"cauliflower rice.\"</li><li>Heat 1T butter and 1T oil in a large skillet over medium heat. Add garlic and the white and light green pieces of scallion. Sauté about a minute.</li><li>Add the cauliflower to the pan. Stir to coat with oil, then spread out in pan and let sit; you want it cook a bit and to caramelize (get a bit brown), which will bring out the sweetness. After a couple of minutes, stir and spread out again.</li><li>Add cold rice (it separates easily, so it won't clump up during cooking), plus the additional grapeseed and coconut oil or butter. Raise heat to medium-high. Toss everything together and, again, spread the mixture out over the whole pan and press a bit into the bottom. Let it sit for about two minutes—so the rice can get toasted and a little crispy. Add the peas and broccoli and stir again. Drizzle soy sauce and toasted sesame oil over rice.</li><li>Cook for another minute or so and turn off heat. Add chopped scallion tops and toss.</li><li>I like to toast some sesame seeds in a dry pan; I sprinkle these and some more raw, chopped scallion over the top of the rice for added flavor and crunch.</li><li>Season to taste with salt and, if you'd like, more soy sauce. Keep in mind that if you're serving this with something salty and saucy (ie. teriyaki chicken) you may want to hold off on adding too much salt to the fried rice.</li></ol>",
    diets: [
      "gluten free",
      "dairy free",
      "paleolithic",
      "lacto ovo vegetarian",
      "primal",
    ],
  },
  {
    id: 798400,
    title: "Spicy Black-Eyed Pea Curry with Swiss Chard and Roasted Eggplant",
    image: "https://spoonacular.com/recipeImages/798400-312x231.jpg",
    dishTypes: ["side dish"],
    summary:
      'The recipe Spicy Black-Eyed Pea Curry with Swiss Chard and Roasted Eggplant is ready <b>in roughly 45 minutes</b> and is definitely a spectacular <b>gluten free and vegan</b> option for lovers of Indian food. This recipe makes 6 servings with <b>130 calories</b>, <b>7g of protein</b>, and <b>2g of fat</b> each. For <b>99 cents per serving</b>, this recipe <b>covers 21%</b> of your daily requirements of vitamins and minerals. A few people made this recipe, and 32 would say it hit the spot. A mixture of chilies, olive oil, garam masala, and a handful of other ingredients are all it takes to make this recipe so delicious. All things considered, we decided this recipe <b>deserves a spoonacular score of 98%</b>. This score is amazing. Try <a href="https://spoonacular.com/recipes/black-eyed-peas-in-a-spicy-goan-curry-31050">Black-eyed Peas In A Spicy Goan Curry</a>, <a href="https://spoonacular.com/recipes/black-eyed-peas-in-a-spicy-goan-curry-31057">Black-eyed Peas In A Spicy Goan Curry</a>, and <a href="https://spoonacular.com/recipes/roasted-butternut-squash-black-bean-and-swiss-chard-quinoa-bibimbap-247604">Roasted Butternut Squash, Black Bean and Swiss Chard Quinoa Bibimbap</a> for similar recipes.',
    healthScore: 87,
    instructions:
      "<ol><li><span></span>Remove the cauliflower's tough stem and reserve for another use. Using a food processor, pulse cauliflower florets until they resemble rice or couscous. You should end up with around four cups of \"cauliflower rice.\"</li><li>Heat 1T butter and 1T oil in a large skillet over medium heat. Add garlic and the white and light green pieces of scallion. Sauté about a minute.</li><li>Add the cauliflower to the pan. Stir to coat with oil, then spread out in pan and let sit; you want it cook a bit and to caramelize (get a bit brown), which will bring out the sweetness. After a couple of minutes, stir and spread out again.</li><li>Add cold rice (it separates easily, so it won't clump up during cooking), plus the additional grapeseed and coconut oil or butter. Raise heat to medium-high. Toss everything together and, again, spread the mixture out over the whole pan and press a bit into the bottom. Let it sit for about two minutes—so the rice can get toasted and a little crispy. Add the peas and broccoli and stir again. Drizzle soy sauce and toasted sesame oil over rice.</li><li>Cook for another minute or so and turn off heat. Add chopped scallion tops and toss.</li><li>I like to toast some sesame seeds in a dry pan; I sprinkle these and some more raw, chopped scallion over the top of the rice for added flavor and crunch.</li><li>Season to taste with salt and, if you'd like, more soy sauce. Keep in mind that if you're serving this with something salty and saucy (ie. teriyaki chicken) you may want to hold off on adding too much salt to the fried rice.</li></ol>",
    diets: ["gluten free", "dairy free", "lacto ovo vegetarian", "vegan"],
  },
  {
    id: 756814,
    title: "Powerhouse Almond Matcha Superfood Smoothie",
    image: "https://spoonacular.com/recipeImages/756814-312x231.jpg",
    dishTypes: ["side dish"],
    summary:
      'Powerhouse Almond Matcha Superfood Smoothie might be just the morn meal you are searching for. This recipe makes 2 servings with <b>294 calories</b>, <b>11g of protein</b>, and <b>13g of fat</b> each. For <b>$2.59 per serving</b>, this recipe <b>covers 27%</b> of your daily requirements of vitamins and minerals. If you have pineapple, almond milk, banana, and a few other ingredients on hand, you can make it. 80 people were impressed by this recipe. It is a good option if you\'re following a <b>gluten free, dairy free, and whole 30</b> diet. From preparation to the plate, this recipe takes around <b>10 minutes</b>. All things considered, we decided this recipe <b>deserves a spoonacular score of 98%</b>. This score is tremendous. Try <a href="https://spoonacular.com/recipes/powerhouse-golden-turmeric-smoothie-882363">Powerhouse Golden Turmeric Smoothie</a>, <a href="https://spoonacular.com/recipes/matcha-almond-layer-cake-with-matcha-frosting-523362">Matchan Almond Layer Cake with Matcha Frosting</a>, and <a href="https://spoonacular.com/recipes/minty-matcha-nanaimo-bars-a-decadent-superfood-treat-704047">Minty Matcha Nanaimo Bars: A Decadent Superfood Treat</a> for similar recipes.',
    healthScore: 54,
    instructions:
      "<ol><li><span></span>Remove the cauliflower's tough stem and reserve for another use. Using a food processor, pulse cauliflower florets until they resemble rice or couscous. You should end up with around four cups of \"cauliflower rice.\"</li><li>Heat 1T butter and 1T oil in a large skillet over medium heat. Add garlic and the white and light green pieces of scallion. Sauté about a minute.</li><li>Add the cauliflower to the pan. Stir to coat with oil, then spread out in pan and let sit; you want it cook a bit and to caramelize (get a bit brown), which will bring out the sweetness. After a couple of minutes, stir and spread out again.</li><li>Add cold rice (it separates easily, so it won't clump up during cooking), plus the additional grapeseed and coconut oil or butter. Raise heat to medium-high. Toss everything together and, again, spread the mixture out over the whole pan and press a bit into the bottom. Let it sit for about two minutes—so the rice can get toasted and a little crispy. Add the peas and broccoli and stir again. Drizzle soy sauce and toasted sesame oil over rice.</li><li>Cook for another minute or so and turn off heat. Add chopped scallion tops and toss.</li><li>I like to toast some sesame seeds in a dry pan; I sprinkle these and some more raw, chopped scallion over the top of the rice for added flavor and crunch.</li><li>Season to taste with salt and, if you'd like, more soy sauce. Keep in mind that if you're serving this with something salty and saucy (ie. teriyaki chicken) you may want to hold off on adding too much salt to the fried rice.</li></ol>",
    diets: ["gluten free", "dairy free", "whole 30"],
  },
  {
    id: 729366,
    title: "Plantain Salad",
    image: "https://spoonacular.com/recipeImages/729366-312x231.jpg",
    dishTypes: ["salad"],
    summary:
      'Plantain Salad might be just the main course you are searching for. This gluten free and pescatarian recipe serves 1 and costs <b>$5.6 per serving</b>. One serving contains <b>639 calories</b>, <b>20g of protein</b>, and <b>18g of fat</b>. Several people made this recipe, and 126 would say it hit the spot. A mixture of vegetable oil, finger of plantain, tomatoes, and a handful of other ingredients are all it takes to make this recipe so delicious. To use up the vegetable oil you could follow this main course with the <a href="https://spoonacular.com/recipes/blueberry-coffee-cake-sundaysupper-511062">Blueberry Coffee Cake #SundaySupper</a> as a dessert. From preparation to the plate, this recipe takes roughly <b>45 minutes</b>. All things considered, we decided this recipe <b>deserves a spoonacular score of 99%</b>. This score is excellent. Try <a href="https://spoonacular.com/recipes/how-to-spiralize-a-plantain-plantain-rice-and-beans-563745">How to Spiralize a Plantain & Plantain “Rice” and Beans</a>, <a href="https://spoonacular.com/recipes/honey-mustard-crunchy-chicken-plantain-salad-509763">Honey Mustard Crunchy Chicken Plantain Salad</a>, and <a href="https://spoonacular.com/recipes/plantain-and-coconut-pork-patties-with-a-tropical-mango-and-cucumber-salad-550923">Plantain and Coconut Pork Patties with a Tropical Mango and Cucumber Salad</a> for similar recipes.',
    healthScore: 72,
    instructions:
      "<ol><li><span></span>Remove the cauliflower's tough stem and reserve for another use. Using a food processor, pulse cauliflower florets until they resemble rice or couscous. You should end up with around four cups of \"cauliflower rice.\"</li><li>Heat 1T butter and 1T oil in a large skillet over medium heat. Add garlic and the white and light green pieces of scallion. Sauté about a minute.</li><li>Add the cauliflower to the pan. Stir to coat with oil, then spread out in pan and let sit; you want it cook a bit and to caramelize (get a bit brown), which will bring out the sweetness. After a couple of minutes, stir and spread out again.</li><li>Add cold rice (it separates easily, so it won't clump up during cooking), plus the additional grapeseed and coconut oil or butter. Raise heat to medium-high. Toss everything together and, again, spread the mixture out over the whole pan and press a bit into the bottom. Let it sit for about two minutes—so the rice can get toasted and a little crispy. Add the peas and broccoli and stir again. Drizzle soy sauce and toasted sesame oil over rice.</li><li>Cook for another minute or so and turn off heat. Add chopped scallion tops and toss.</li><li>I like to toast some sesame seeds in a dry pan; I sprinkle these and some more raw, chopped scallion over the top of the rice for added flavor and crunch.</li><li>Season to taste with salt and, if you'd like, more soy sauce. Keep in mind that if you're serving this with something salty and saucy (ie. teriyaki chicken) you may want to hold off on adding too much salt to the fried rice.</li></ol>",
    diets: ["gluten free", "primal", "pescatarian"],
  },
  {
    id: 715769,
    title: "Broccolini Quinoa Pilaf",
    image: "https://spoonacular.com/recipeImages/715769-312x231.jpg",
    dishTypes: ["lunch", "main course", "main dish", "dinner"],
    summary:
      'If you want to add more <b>Mediterranean</b> recipes to your recipe box, Broccolini Quinoa Pilaf might be a recipe you should try. One portion of this dish contains around <b>20g of protein</b>, <b>31g of fat</b>, and a total of <b>625 calories</b>. This recipe serves 2 and costs $4.14 per serving. A few people really liked this main course. 95 people have made this recipe and would make it again. Head to the store and pick up quinoa, garlic clove, olive oil, and a few other things to make it today. From preparation to the plate, this recipe takes roughly <b>30 minutes</b>. It is a good option if you\'re following a <b>gluten free, dairy free, lacto ovo vegetarian, and vegan</b> diet. It is brought to you by Pick Fresh Foods. All things considered, we decided this recipe <b>deserves a spoonacular score of 98%</b>. This score is awesome. Similar recipes include <a href="https://spoonacular.com/recipes/spring-broccolini-kale-quinoa-bowls-734866">Spring Broccolini & Kale Quinoa Bowls</a>, <a href="https://spoonacular.com/recipes/orange-sesame-salmon-with-quinoa-broccolini-839832">Orange-Sesame Salmon with Quinoa & Broccolini</a>, and <a href="https://spoonacular.com/recipes/black-pepper-goat-cheese-and-chard-quinoa-with-roasted-broccolini-625829">Black Pepper Goat Cheese and Chard Quinoa with Roasted Broccolini</a>.',
    healthScore: 74,
    instructions:
      "<ol><li><span></span>Remove the cauliflower's tough stem and reserve for another use. Using a food processor, pulse cauliflower florets until they resemble rice or couscous. You should end up with around four cups of \"cauliflower rice.\"</li><li>Heat 1T butter and 1T oil in a large skillet over medium heat. Add garlic and the white and light green pieces of scallion. Sauté about a minute.</li><li>Add the cauliflower to the pan. Stir to coat with oil, then spread out in pan and let sit; you want it cook a bit and to caramelize (get a bit brown), which will bring out the sweetness. After a couple of minutes, stir and spread out again.</li><li>Add cold rice (it separates easily, so it won't clump up during cooking), plus the additional grapeseed and coconut oil or butter. Raise heat to medium-high. Toss everything together and, again, spread the mixture out over the whole pan and press a bit into the bottom. Let it sit for about two minutes—so the rice can get toasted and a little crispy. Add the peas and broccoli and stir again. Drizzle soy sauce and toasted sesame oil over rice.</li><li>Cook for another minute or so and turn off heat. Add chopped scallion tops and toss.</li><li>I like to toast some sesame seeds in a dry pan; I sprinkle these and some more raw, chopped scallion over the top of the rice for added flavor and crunch.</li><li>Season to taste with salt and, if you'd like, more soy sauce. Keep in mind that if you're serving this with something salty and saucy (ie. teriyaki chicken) you may want to hold off on adding too much salt to the fried rice.</li></ol>",
    diets: ["gluten free", "dairy free", "lacto ovo vegetarian", "vegan"],
  },
  {
    id: 782600,
    title: "Quinoa Salad with Vegetables and Cashews",
    image: "https://spoonacular.com/recipeImages/782600-312x231.jpg",
    dishTypes: ["salad"],
    summary:
      'You can never have too many side dish recipes, so give Quinoa Salad with Vegetables and Cashews a try. This recipe makes 6 servings with <b>487 calories</b>, <b>9g of protein</b>, and <b>39g of fat</b> each. For <b>$1.58 per serving</b>, this recipe <b>covers 24%</b> of your daily requirements of vitamins and minerals. This recipe from foodandspice.blogspot.com has 88 fans. If you have quinoa, sunflower seeds, sesame oil, and a few other ingredients on hand, you can make it. From preparation to the plate, this recipe takes approximately <b>45 minutes</b>. It is a good option if you\'re following a <b>gluten free and vegan</b> diet. All things considered, we decided this recipe <b>deserves a spoonacular score of 98%</b>. This score is tremendous. Try <a href="https://spoonacular.com/recipes/cashews-and-vegetables-114102">Cashews and Vegetables</a>, <a href="https://spoonacular.com/recipes/lemony-quinoa-salad-with-shaved-vegetables-27876">Lemony Quinoa Salad with Shaved Vegetables</a>, and <a href="https://spoonacular.com/recipes/grill-roasted-vegetables-and-quinoa-salad-757439">Grill-Roasted Vegetables and Quinoa Salad</a> for similar recipes.',
    healthScore: 66,
    instructions:
      "<ol><li><span></span>Remove the cauliflower's tough stem and reserve for another use. Using a food processor, pulse cauliflower florets until they resemble rice or couscous. You should end up with around four cups of \"cauliflower rice.\"</li><li>Heat 1T butter and 1T oil in a large skillet over medium heat. Add garlic and the white and light green pieces of scallion. Sauté about a minute.</li><li>Add the cauliflower to the pan. Stir to coat with oil, then spread out in pan and let sit; you want it cook a bit and to caramelize (get a bit brown), which will bring out the sweetness. After a couple of minutes, stir and spread out again.</li><li>Add cold rice (it separates easily, so it won't clump up during cooking), plus the additional grapeseed and coconut oil or butter. Raise heat to medium-high. Toss everything together and, again, spread the mixture out over the whole pan and press a bit into the bottom. Let it sit for about two minutes—so the rice can get toasted and a little crispy. Add the peas and broccoli and stir again. Drizzle soy sauce and toasted sesame oil over rice.</li><li>Cook for another minute or so and turn off heat. Add chopped scallion tops and toss.</li><li>I like to toast some sesame seeds in a dry pan; I sprinkle these and some more raw, chopped scallion over the top of the rice for added flavor and crunch.</li><li>Season to taste with salt and, if you'd like, more soy sauce. Keep in mind that if you're serving this with something salty and saucy (ie. teriyaki chicken) you may want to hold off on adding too much salt to the fried rice.</li></ol>",
    diets: ["gluten free", "dairy free", "lacto ovo vegetarian", "vegan"],
  },
  {
    id: 642605,
    title: "Farro With Mushrooms and Asparagus",
    image: "https://spoonacular.com/recipeImages/642605-312x231.jpg",
    dishTypes: ["side dish"],
    summary:
      'Need a <b>dairy free and vegetarian side dish</b>? Farro With Mushrooms and Asparagus could be an excellent recipe to try. This recipe makes 4 servings with <b>365 calories</b>, <b>12g of protein</b>, and <b>9g of fat</b> each. For <b>$3.94 per serving</b>, this recipe <b>covers 23%</b> of your daily requirements of vitamins and minerals. From preparation to the plate, this recipe takes around <b>1 hour and 15 minutes</b>. This recipe is liked by 47 foodies and cooks. If you have onion, chicken stock, garlic, and a few other ingredients on hand, you can make it. All things considered, we decided this recipe <b>deserves a spoonacular score of 98%</b>. This score is amazing. Similar recipes include <a href="https://spoonacular.com/recipes/farro-risotto-with-wild-mushrooms-and-asparagus-495316">Farro Risotto with Wild Mushrooms and Asparagus</a>, <a href="https://spoonacular.com/recipes/farro-with-asparagus-hazelnuts-and-kale-topped-with-roasted-mushrooms-298005">Farro with Asparagus, Hazelnuts and Kale Topped with Roasted Mushrooms</a>, and <a href="https://spoonacular.com/recipes/farro-and-porcini-mushrooms-farro-con-funghi-40485">Farro And Porcini Mushrooms (farro Con Funghi)</a>.',
    healthScore: 80,
    instructions:
      "<ol><li><span></span>Remove the cauliflower's tough stem and reserve for another use. Using a food processor, pulse cauliflower florets until they resemble rice or couscous. You should end up with around four cups of \"cauliflower rice.\"</li><li>Heat 1T butter and 1T oil in a large skillet over medium heat. Add garlic and the white and light green pieces of scallion. Sauté about a minute.</li><li>Add the cauliflower to the pan. Stir to coat with oil, then spread out in pan and let sit; you want it cook a bit and to caramelize (get a bit brown), which will bring out the sweetness. After a couple of minutes, stir and spread out again.</li><li>Add cold rice (it separates easily, so it won't clump up during cooking), plus the additional grapeseed and coconut oil or butter. Raise heat to medium-high. Toss everything together and, again, spread the mixture out over the whole pan and press a bit into the bottom. Let it sit for about two minutes—so the rice can get toasted and a little crispy. Add the peas and broccoli and stir again. Drizzle soy sauce and toasted sesame oil over rice.</li><li>Cook for another minute or so and turn off heat. Add chopped scallion tops and toss.</li><li>I like to toast some sesame seeds in a dry pan; I sprinkle these and some more raw, chopped scallion over the top of the rice for added flavor and crunch.</li><li>Season to taste with salt and, if you'd like, more soy sauce. Keep in mind that if you're serving this with something salty and saucy (ie. teriyaki chicken) you may want to hold off on adding too much salt to the fried rice.</li></ol>",
    diets: ["dairy free", "lacto ovo vegetarian"],
  },
];
